services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    networks:
      - service
  socket-server:
    build:
      context: ./messsage-socket
      dockerfile: DockerFile
    container_name: socket-server
    restart: always
    image: encrypted-messenger/socket-server:local
    ports:
      - 3001:3001
    environment:
      SERVER_PORT: 3001
      GRPC_BACKEND_ADDR: backend:8082
      RABBITMQ_URL: amqp://test:test@rabbitmq:5672/
    depends_on:
      - backend
      - rabbitmq
    networks:
      - service
  middleware:
    build:
      context: ./middleware
      dockerfile: DockerFile
    container_name: middleware
    restart: always
    image: encrypted-messenger/middleware:local
    ports:
      - 8081:8081
    environment:
      SERVER_PORT: 8081
      GRPC_BACKEND_ADDR: backend:8082
      RABBITMQ_URL: amqp://test:test@rabbitmq:5672/
    depends_on:
      - backend
      - rabbitmq
    networks:
      - service
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: backend
    restart: always
    image: encrypted-messenger/backend:local
    ports:
      - 8082:8082
    environment:
      JWT_SECRET_KEY: test
    networks:
      - service
networks:
  service:
    external: false
