// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.service;

@kotlin.jvm.JvmName("-initializepingResponse")
public inline fun pingResponse(block: com.service.PingResponseKt.Dsl.() -> kotlin.Unit): com.service.PingResponse =
  com.service.PingResponseKt.Dsl._create(com.service.PingResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.service.PingResponse`
 */
public object PingResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.service.PingResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.service.PingResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.service.PingResponse = _builder.build()

    /**
     * `string message = 1;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.service.PingResponse.copy(block: `com.service`.PingResponseKt.Dsl.() -> kotlin.Unit): com.service.PingResponse =
  `com.service`.PingResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

