//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: middleware/middleware.proto

package com.middleware;

@kotlin.jvm.JvmSynthetic
inline fun pingResponse(block: com.middleware.PingResponseKt.Dsl.() -> kotlin.Unit): com.middleware.PingResponse =
  com.middleware.PingResponseKt.Dsl._create(com.middleware.PingResponse.newBuilder()).apply { block() }._build()
object PingResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.middleware.PingResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.middleware.PingResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.middleware.PingResponse = _builder.build()

    /**
     * <code>string message = 1;</code>
     */
    var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 1;</code>
     */
    fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.middleware.PingResponse.copy(block: com.middleware.PingResponseKt.Dsl.() -> kotlin.Unit): com.middleware.PingResponse =
  com.middleware.PingResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
