// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.services;

@kotlin.jvm.JvmName("-initializeauthResponse")
public inline fun authResponse(block: com.services.AuthResponseKt.Dsl.() -> kotlin.Unit): com.services.Auth.AuthResponse =
  com.services.AuthResponseKt.Dsl._create(com.services.Auth.AuthResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `AuthResponse`
 */
public object AuthResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.services.Auth.AuthResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.Auth.AuthResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.Auth.AuthResponse = _builder.build()

    /**
     * `optional string token = 1;`
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * `optional string token = 1;`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
    /**
     * `optional string token = 1;`
     * @return Whether the token field is set.
     */
    public fun hasToken(): kotlin.Boolean {
      return _builder.hasToken()
    }

    /**
     * `optional bool isVerified = 2;`
     */
    public var isVerified: kotlin.Boolean
      @JvmName("getIsVerified")
      get() = _builder.getIsVerified()
      @JvmName("setIsVerified")
      set(value) {
        _builder.setIsVerified(value)
      }
    /**
     * `optional bool isVerified = 2;`
     */
    public fun clearIsVerified() {
      _builder.clearIsVerified()
    }
    /**
     * `optional bool isVerified = 2;`
     * @return Whether the isVerified field is set.
     */
    public fun hasIsVerified(): kotlin.Boolean {
      return _builder.hasIsVerified()
    }

    /**
     * `optional string error = 3;`
     */
    public var error: kotlin.String
      @JvmName("getError")
      get() = _builder.getError()
      @JvmName("setError")
      set(value) {
        _builder.setError(value)
      }
    /**
     * `optional string error = 3;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `optional string error = 3;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }

    /**
     * `optional .User user = 4;`
     */
    public var user: com.services.UserOuterClass.User
      @JvmName("getUser")
      get() = _builder.getUser()
      @JvmName("setUser")
      set(value) {
        _builder.setUser(value)
      }
    /**
     * `optional .User user = 4;`
     */
    public fun clearUser() {
      _builder.clearUser()
    }
    /**
     * `optional .User user = 4;`
     * @return Whether the user field is set.
     */
    public fun hasUser(): kotlin.Boolean {
      return _builder.hasUser()
    }
    public val AuthResponseKt.Dsl.userOrNull: com.services.UserOuterClass.User?
      get() = _builder.userOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.services.Auth.AuthResponse.copy(block: `com.services`.AuthResponseKt.Dsl.() -> kotlin.Unit): com.services.Auth.AuthResponse =
  `com.services`.AuthResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.services.Auth.AuthResponseOrBuilder.userOrNull: com.services.UserOuterClass.User?
  get() = if (hasUser()) getUser() else null

