// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

package com.services;

public final class ContactOuterClass {
  private ContactOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContactOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Contact)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string phoneNumber = 3;</code>
     * @return The phoneNumber.
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>string phoneNumber = 3;</code>
     * @return The bytes for phoneNumber.
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>string countryCode = 4;</code>
     * @return Whether the countryCode field is set.
     */
    boolean hasCountryCode();
    /**
     * <code>string countryCode = 4;</code>
     * @return The countryCode.
     */
    java.lang.String getCountryCode();
    /**
     * <code>string countryCode = 4;</code>
     * @return The bytes for countryCode.
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <code>string profilePicture = 5;</code>
     * @return Whether the profilePicture field is set.
     */
    boolean hasProfilePicture();
    /**
     * <code>string profilePicture = 5;</code>
     * @return The profilePicture.
     */
    java.lang.String getProfilePicture();
    /**
     * <code>string profilePicture = 5;</code>
     * @return The bytes for profilePicture.
     */
    com.google.protobuf.ByteString
        getProfilePictureBytes();

    /**
     * <code>bool isVerified = 6;</code>
     * @return Whether the isVerified field is set.
     */
    boolean hasIsVerified();
    /**
     * <code>bool isVerified = 6;</code>
     * @return The isVerified.
     */
    boolean getIsVerified();

    /**
     * <code>string uuid = 7;</code>
     * @return Whether the uuid field is set.
     */
    boolean hasUuid();
    /**
     * <code>string uuid = 7;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 7;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>string pubKey = 8;</code>
     * @return Whether the pubKey field is set.
     */
    boolean hasPubKey();
    /**
     * <code>string pubKey = 8;</code>
     * @return The pubKey.
     */
    java.lang.String getPubKey();
    /**
     * <code>string pubKey = 8;</code>
     * @return The bytes for pubKey.
     */
    com.google.protobuf.ByteString
        getPubKeyBytes();
  }
  /**
   * Protobuf type {@code Contact}
   */
  public static final class Contact extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Contact)
      ContactOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Contact.newBuilder() to construct.
    private Contact(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contact() {
      id_ = "";
      name_ = "";
      phoneNumber_ = "";
      countryCode_ = "";
      profilePicture_ = "";
      uuid_ = "";
      pubKey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Contact();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Contact(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              countryCode_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              profilePicture_ = s;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              isVerified_ = input.readBool();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              uuid_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              pubKey_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.services.ContactOuterClass.internal_static_Contact_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.services.ContactOuterClass.internal_static_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.services.ContactOuterClass.Contact.class, com.services.ContactOuterClass.Contact.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object phoneNumber_;
    /**
     * <code>string phoneNumber = 3;</code>
     * @return The phoneNumber.
     */
    @java.lang.Override
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string phoneNumber = 3;</code>
     * @return The bytes for phoneNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYCODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object countryCode_;
    /**
     * <code>string countryCode = 4;</code>
     * @return Whether the countryCode field is set.
     */
    @java.lang.Override
    public boolean hasCountryCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string countryCode = 4;</code>
     * @return The countryCode.
     */
    @java.lang.Override
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string countryCode = 4;</code>
     * @return The bytes for countryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFILEPICTURE_FIELD_NUMBER = 5;
    private volatile java.lang.Object profilePicture_;
    /**
     * <code>string profilePicture = 5;</code>
     * @return Whether the profilePicture field is set.
     */
    @java.lang.Override
    public boolean hasProfilePicture() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>string profilePicture = 5;</code>
     * @return The profilePicture.
     */
    @java.lang.Override
    public java.lang.String getProfilePicture() {
      java.lang.Object ref = profilePicture_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profilePicture_ = s;
        return s;
      }
    }
    /**
     * <code>string profilePicture = 5;</code>
     * @return The bytes for profilePicture.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProfilePictureBytes() {
      java.lang.Object ref = profilePicture_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profilePicture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISVERIFIED_FIELD_NUMBER = 6;
    private boolean isVerified_;
    /**
     * <code>bool isVerified = 6;</code>
     * @return Whether the isVerified field is set.
     */
    @java.lang.Override
    public boolean hasIsVerified() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>bool isVerified = 6;</code>
     * @return The isVerified.
     */
    @java.lang.Override
    public boolean getIsVerified() {
      return isVerified_;
    }

    public static final int UUID_FIELD_NUMBER = 7;
    private volatile java.lang.Object uuid_;
    /**
     * <code>string uuid = 7;</code>
     * @return Whether the uuid field is set.
     */
    @java.lang.Override
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>string uuid = 7;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 7;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBKEY_FIELD_NUMBER = 8;
    private volatile java.lang.Object pubKey_;
    /**
     * <code>string pubKey = 8;</code>
     * @return Whether the pubKey field is set.
     */
    @java.lang.Override
    public boolean hasPubKey() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>string pubKey = 8;</code>
     * @return The pubKey.
     */
    @java.lang.Override
    public java.lang.String getPubKey() {
      java.lang.Object ref = pubKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pubKey_ = s;
        return s;
      }
    }
    /**
     * <code>string pubKey = 8;</code>
     * @return The bytes for pubKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPubKeyBytes() {
      java.lang.Object ref = pubKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneNumber_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, countryCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, profilePicture_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(6, isVerified_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, uuid_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pubKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneNumber_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, countryCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, profilePicture_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isVerified_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, uuid_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pubKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.services.ContactOuterClass.Contact)) {
        return super.equals(obj);
      }
      com.services.ContactOuterClass.Contact other = (com.services.ContactOuterClass.Contact) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPhoneNumber()
          .equals(other.getPhoneNumber())) return false;
      if (hasCountryCode() != other.hasCountryCode()) return false;
      if (hasCountryCode()) {
        if (!getCountryCode()
            .equals(other.getCountryCode())) return false;
      }
      if (hasProfilePicture() != other.hasProfilePicture()) return false;
      if (hasProfilePicture()) {
        if (!getProfilePicture()
            .equals(other.getProfilePicture())) return false;
      }
      if (hasIsVerified() != other.hasIsVerified()) return false;
      if (hasIsVerified()) {
        if (getIsVerified()
            != other.getIsVerified()) return false;
      }
      if (hasUuid() != other.hasUuid()) return false;
      if (hasUuid()) {
        if (!getUuid()
            .equals(other.getUuid())) return false;
      }
      if (hasPubKey() != other.hasPubKey()) return false;
      if (hasPubKey()) {
        if (!getPubKey()
            .equals(other.getPubKey())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      if (hasCountryCode()) {
        hash = (37 * hash) + COUNTRYCODE_FIELD_NUMBER;
        hash = (53 * hash) + getCountryCode().hashCode();
      }
      if (hasProfilePicture()) {
        hash = (37 * hash) + PROFILEPICTURE_FIELD_NUMBER;
        hash = (53 * hash) + getProfilePicture().hashCode();
      }
      if (hasIsVerified()) {
        hash = (37 * hash) + ISVERIFIED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsVerified());
      }
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasPubKey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubKey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.services.ContactOuterClass.Contact parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.services.ContactOuterClass.Contact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.services.ContactOuterClass.Contact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.services.ContactOuterClass.Contact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.services.ContactOuterClass.Contact prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Contact}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Contact)
        com.services.ContactOuterClass.ContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.services.ContactOuterClass.internal_static_Contact_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.services.ContactOuterClass.internal_static_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.services.ContactOuterClass.Contact.class, com.services.ContactOuterClass.Contact.Builder.class);
      }

      // Construct using com.services.ContactOuterClass.Contact.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        phoneNumber_ = "";

        countryCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        profilePicture_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isVerified_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        pubKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.services.ContactOuterClass.internal_static_Contact_descriptor;
      }

      @java.lang.Override
      public com.services.ContactOuterClass.Contact getDefaultInstanceForType() {
        return com.services.ContactOuterClass.Contact.getDefaultInstance();
      }

      @java.lang.Override
      public com.services.ContactOuterClass.Contact build() {
        com.services.ContactOuterClass.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.services.ContactOuterClass.Contact buildPartial() {
        com.services.ContactOuterClass.Contact result = new com.services.ContactOuterClass.Contact(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.phoneNumber_ = phoneNumber_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.countryCode_ = countryCode_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.profilePicture_ = profilePicture_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isVerified_ = isVerified_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pubKey_ = pubKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.services.ContactOuterClass.Contact) {
          return mergeFrom((com.services.ContactOuterClass.Contact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.services.ContactOuterClass.Contact other) {
        if (other == com.services.ContactOuterClass.Contact.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        if (other.hasCountryCode()) {
          bitField0_ |= 0x00000001;
          countryCode_ = other.countryCode_;
          onChanged();
        }
        if (other.hasProfilePicture()) {
          bitField0_ |= 0x00000002;
          profilePicture_ = other.profilePicture_;
          onChanged();
        }
        if (other.hasIsVerified()) {
          setIsVerified(other.getIsVerified());
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000008;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasPubKey()) {
          bitField0_ |= 0x00000010;
          pubKey_ = other.pubKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.services.ContactOuterClass.Contact parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.services.ContactOuterClass.Contact) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>string phoneNumber = 3;</code>
       * @return The phoneNumber.
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phoneNumber = 3;</code>
       * @return The bytes for phoneNumber.
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phoneNumber = 3;</code>
       * @param value The phoneNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 3;</code>
       * @param value The bytes for phoneNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <code>string countryCode = 4;</code>
       * @return Whether the countryCode field is set.
       */
      public boolean hasCountryCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>string countryCode = 4;</code>
       * @return The countryCode.
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string countryCode = 4;</code>
       * @return The bytes for countryCode.
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string countryCode = 4;</code>
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string countryCode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        countryCode_ = getDefaultInstance().getCountryCode();
        onChanged();
        return this;
      }
      /**
       * <code>string countryCode = 4;</code>
       * @param value The bytes for countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        countryCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object profilePicture_ = "";
      /**
       * <code>string profilePicture = 5;</code>
       * @return Whether the profilePicture field is set.
       */
      public boolean hasProfilePicture() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>string profilePicture = 5;</code>
       * @return The profilePicture.
       */
      public java.lang.String getProfilePicture() {
        java.lang.Object ref = profilePicture_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          profilePicture_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string profilePicture = 5;</code>
       * @return The bytes for profilePicture.
       */
      public com.google.protobuf.ByteString
          getProfilePictureBytes() {
        java.lang.Object ref = profilePicture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          profilePicture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string profilePicture = 5;</code>
       * @param value The profilePicture to set.
       * @return This builder for chaining.
       */
      public Builder setProfilePicture(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        profilePicture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string profilePicture = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProfilePicture() {
        bitField0_ = (bitField0_ & ~0x00000002);
        profilePicture_ = getDefaultInstance().getProfilePicture();
        onChanged();
        return this;
      }
      /**
       * <code>string profilePicture = 5;</code>
       * @param value The bytes for profilePicture to set.
       * @return This builder for chaining.
       */
      public Builder setProfilePictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        profilePicture_ = value;
        onChanged();
        return this;
      }

      private boolean isVerified_ ;
      /**
       * <code>bool isVerified = 6;</code>
       * @return Whether the isVerified field is set.
       */
      @java.lang.Override
      public boolean hasIsVerified() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>bool isVerified = 6;</code>
       * @return The isVerified.
       */
      @java.lang.Override
      public boolean getIsVerified() {
        return isVerified_;
      }
      /**
       * <code>bool isVerified = 6;</code>
       * @param value The isVerified to set.
       * @return This builder for chaining.
       */
      public Builder setIsVerified(boolean value) {
        bitField0_ |= 0x00000004;
        isVerified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isVerified = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsVerified() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isVerified_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 7;</code>
       * @return Whether the uuid field is set.
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>string uuid = 7;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 7;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 7;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 7;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pubKey_ = "";
      /**
       * <code>string pubKey = 8;</code>
       * @return Whether the pubKey field is set.
       */
      public boolean hasPubKey() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>string pubKey = 8;</code>
       * @return The pubKey.
       */
      public java.lang.String getPubKey() {
        java.lang.Object ref = pubKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pubKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pubKey = 8;</code>
       * @return The bytes for pubKey.
       */
      public com.google.protobuf.ByteString
          getPubKeyBytes() {
        java.lang.Object ref = pubKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pubKey = 8;</code>
       * @param value The pubKey to set.
       * @return This builder for chaining.
       */
      public Builder setPubKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        pubKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pubKey = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pubKey_ = getDefaultInstance().getPubKey();
        onChanged();
        return this;
      }
      /**
       * <code>string pubKey = 8;</code>
       * @param value The bytes for pubKey to set.
       * @return This builder for chaining.
       */
      public Builder setPubKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000010;
        pubKey_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Contact)
    }

    // @@protoc_insertion_point(class_scope:Contact)
    private static final com.services.ContactOuterClass.Contact DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.services.ContactOuterClass.Contact();
    }

    public static com.services.ContactOuterClass.Contact getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contact>
        PARSER = new com.google.protobuf.AbstractParser<Contact>() {
      @java.lang.Override
      public Contact parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contact(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Contact> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contact> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.services.ContactOuterClass.Contact getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactsListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ContactsList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    java.util.List<com.services.ContactOuterClass.Contact> 
        getContactsList();
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    com.services.ContactOuterClass.Contact getContacts(int index);
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    int getContactsCount();
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    java.util.List<? extends com.services.ContactOuterClass.ContactOrBuilder> 
        getContactsOrBuilderList();
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    com.services.ContactOuterClass.ContactOrBuilder getContactsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ContactsList}
   */
  public static final class ContactsList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ContactsList)
      ContactsListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactsList.newBuilder() to construct.
    private ContactsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactsList() {
      contacts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContactsList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactsList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                contacts_ = new java.util.ArrayList<com.services.ContactOuterClass.Contact>();
                mutable_bitField0_ |= 0x00000001;
              }
              contacts_.add(
                  input.readMessage(com.services.ContactOuterClass.Contact.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          contacts_ = java.util.Collections.unmodifiableList(contacts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.services.ContactOuterClass.internal_static_ContactsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.services.ContactOuterClass.internal_static_ContactsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.services.ContactOuterClass.ContactsList.class, com.services.ContactOuterClass.ContactsList.Builder.class);
    }

    public static final int CONTACTS_FIELD_NUMBER = 1;
    private java.util.List<com.services.ContactOuterClass.Contact> contacts_;
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.services.ContactOuterClass.Contact> getContactsList() {
      return contacts_;
    }
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.services.ContactOuterClass.ContactOrBuilder> 
        getContactsOrBuilderList() {
      return contacts_;
    }
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    @java.lang.Override
    public int getContactsCount() {
      return contacts_.size();
    }
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    @java.lang.Override
    public com.services.ContactOuterClass.Contact getContacts(int index) {
      return contacts_.get(index);
    }
    /**
     * <code>repeated .Contact contacts = 1;</code>
     */
    @java.lang.Override
    public com.services.ContactOuterClass.ContactOrBuilder getContactsOrBuilder(
        int index) {
      return contacts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contacts_.size(); i++) {
        output.writeMessage(1, contacts_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contacts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contacts_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.services.ContactOuterClass.ContactsList)) {
        return super.equals(obj);
      }
      com.services.ContactOuterClass.ContactsList other = (com.services.ContactOuterClass.ContactsList) obj;

      if (!getContactsList()
          .equals(other.getContactsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContactsCount() > 0) {
        hash = (37 * hash) + CONTACTS_FIELD_NUMBER;
        hash = (53 * hash) + getContactsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.services.ContactOuterClass.ContactsList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.services.ContactOuterClass.ContactsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.services.ContactOuterClass.ContactsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.services.ContactOuterClass.ContactsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.services.ContactOuterClass.ContactsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ContactsList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ContactsList)
        com.services.ContactOuterClass.ContactsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.services.ContactOuterClass.internal_static_ContactsList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.services.ContactOuterClass.internal_static_ContactsList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.services.ContactOuterClass.ContactsList.class, com.services.ContactOuterClass.ContactsList.Builder.class);
      }

      // Construct using com.services.ContactOuterClass.ContactsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContactsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.services.ContactOuterClass.internal_static_ContactsList_descriptor;
      }

      @java.lang.Override
      public com.services.ContactOuterClass.ContactsList getDefaultInstanceForType() {
        return com.services.ContactOuterClass.ContactsList.getDefaultInstance();
      }

      @java.lang.Override
      public com.services.ContactOuterClass.ContactsList build() {
        com.services.ContactOuterClass.ContactsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.services.ContactOuterClass.ContactsList buildPartial() {
        com.services.ContactOuterClass.ContactsList result = new com.services.ContactOuterClass.ContactsList(this);
        int from_bitField0_ = bitField0_;
        if (contactsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            contacts_ = java.util.Collections.unmodifiableList(contacts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contacts_ = contacts_;
        } else {
          result.contacts_ = contactsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.services.ContactOuterClass.ContactsList) {
          return mergeFrom((com.services.ContactOuterClass.ContactsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.services.ContactOuterClass.ContactsList other) {
        if (other == com.services.ContactOuterClass.ContactsList.getDefaultInstance()) return this;
        if (contactsBuilder_ == null) {
          if (!other.contacts_.isEmpty()) {
            if (contacts_.isEmpty()) {
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactsIsMutable();
              contacts_.addAll(other.contacts_);
            }
            onChanged();
          }
        } else {
          if (!other.contacts_.isEmpty()) {
            if (contactsBuilder_.isEmpty()) {
              contactsBuilder_.dispose();
              contactsBuilder_ = null;
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContactsFieldBuilder() : null;
            } else {
              contactsBuilder_.addAllMessages(other.contacts_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.services.ContactOuterClass.ContactsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.services.ContactOuterClass.ContactsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.services.ContactOuterClass.Contact> contacts_ =
        java.util.Collections.emptyList();
      private void ensureContactsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contacts_ = new java.util.ArrayList<com.services.ContactOuterClass.Contact>(contacts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.services.ContactOuterClass.Contact, com.services.ContactOuterClass.Contact.Builder, com.services.ContactOuterClass.ContactOrBuilder> contactsBuilder_;

      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public java.util.List<com.services.ContactOuterClass.Contact> getContactsList() {
        if (contactsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contacts_);
        } else {
          return contactsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public int getContactsCount() {
        if (contactsBuilder_ == null) {
          return contacts_.size();
        } else {
          return contactsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public com.services.ContactOuterClass.Contact getContacts(int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);
        } else {
          return contactsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder setContacts(
          int index, com.services.ContactOuterClass.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.set(index, value);
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder setContacts(
          int index, com.services.ContactOuterClass.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder addContacts(com.services.ContactOuterClass.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder addContacts(
          int index, com.services.ContactOuterClass.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(index, value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder addContacts(
          com.services.ContactOuterClass.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder addContacts(
          int index, com.services.ContactOuterClass.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder addAllContacts(
          java.lang.Iterable<? extends com.services.ContactOuterClass.Contact> values) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contacts_);
          onChanged();
        } else {
          contactsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder clearContacts() {
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public Builder removeContacts(int index) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.remove(index);
          onChanged();
        } else {
          contactsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public com.services.ContactOuterClass.Contact.Builder getContactsBuilder(
          int index) {
        return getContactsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public com.services.ContactOuterClass.ContactOrBuilder getContactsOrBuilder(
          int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);  } else {
          return contactsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public java.util.List<? extends com.services.ContactOuterClass.ContactOrBuilder> 
           getContactsOrBuilderList() {
        if (contactsBuilder_ != null) {
          return contactsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contacts_);
        }
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public com.services.ContactOuterClass.Contact.Builder addContactsBuilder() {
        return getContactsFieldBuilder().addBuilder(
            com.services.ContactOuterClass.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public com.services.ContactOuterClass.Contact.Builder addContactsBuilder(
          int index) {
        return getContactsFieldBuilder().addBuilder(
            index, com.services.ContactOuterClass.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .Contact contacts = 1;</code>
       */
      public java.util.List<com.services.ContactOuterClass.Contact.Builder> 
           getContactsBuilderList() {
        return getContactsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.services.ContactOuterClass.Contact, com.services.ContactOuterClass.Contact.Builder, com.services.ContactOuterClass.ContactOrBuilder> 
          getContactsFieldBuilder() {
        if (contactsBuilder_ == null) {
          contactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.services.ContactOuterClass.Contact, com.services.ContactOuterClass.Contact.Builder, com.services.ContactOuterClass.ContactOrBuilder>(
                  contacts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          contacts_ = null;
        }
        return contactsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ContactsList)
    }

    // @@protoc_insertion_point(class_scope:ContactsList)
    private static final com.services.ContactOuterClass.ContactsList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.services.ContactOuterClass.ContactsList();
    }

    public static com.services.ContactOuterClass.ContactsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactsList>
        PARSER = new com.google.protobuf.AbstractParser<ContactsList>() {
      @java.lang.Override
      public ContactsList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactsList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactsList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.services.ContactOuterClass.ContactsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Contact_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Contact_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContactsList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ContactsList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontact.proto\"\366\001\n\007Contact\022\n\n\002id\030\001 \001(\t\022" +
      "\014\n\004name\030\002 \001(\t\022\023\n\013phoneNumber\030\003 \001(\t\022\030\n\013co" +
      "untryCode\030\004 \001(\tH\000\210\001\001\022\033\n\016profilePicture\030\005" +
      " \001(\tH\001\210\001\001\022\027\n\nisVerified\030\006 \001(\010H\002\210\001\001\022\021\n\004uu" +
      "id\030\007 \001(\tH\003\210\001\001\022\023\n\006pubKey\030\010 \001(\tH\004\210\001\001B\016\n\014_c" +
      "ountryCodeB\021\n\017_profilePictureB\r\n\013_isVeri" +
      "fiedB\007\n\005_uuidB\t\n\007_pubKey\"*\n\014ContactsList" +
      "\022\032\n\010contacts\030\001 \003(\0132\010.ContactB\023\n\014com.serv" +
      "icesZ\003/pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Contact_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Contact_descriptor,
        new java.lang.String[] { "Id", "Name", "PhoneNumber", "CountryCode", "ProfilePicture", "IsVerified", "Uuid", "PubKey", "CountryCode", "ProfilePicture", "IsVerified", "Uuid", "PubKey", });
    internal_static_ContactsList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ContactsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ContactsList_descriptor,
        new java.lang.String[] { "Contacts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
