//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

package com.services;

@kotlin.jvm.JvmSynthetic
inline fun event(block: com.services.EventKt.Dsl.() -> kotlin.Unit): com.services.Message.Event =
  com.services.EventKt.Dsl._create(com.services.Message.Event.newBuilder()).apply { block() }._build()
object EventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.services.Message.Event.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.Message.Event.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.Message.Event = _builder.build()

    /**
     * <code>.EventType type = 1;</code>
     */
    var type: com.services.Message.EventType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>.EventType type = 1;</code>
     */
    fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>string token = 2;</code>
     */
    var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * <code>string token = 2;</code>
     */
    fun clearToken() {
      _builder.clearToken()
    }

    /**
     * <code>.MessageRequest message = 3;</code>
     */
    var message: com.services.Message.MessageRequest
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>.MessageRequest message = 3;</code>
     */
    fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * <code>.MessageRequest message = 3;</code>
     * @return Whether the message field is set.
     */
    fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.services.Message.Event.copy(block: com.services.EventKt.Dsl.() -> kotlin.Unit): com.services.Message.Event =
  com.services.EventKt.Dsl._create(this.toBuilder()).apply { block() }._build()
