//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: hello.proto

package com.services;

@kotlin.jvm.JvmSynthetic
inline fun helloReply(block: com.services.HelloReplyKt.Dsl.() -> kotlin.Unit): com.services.Hello.HelloReply =
  com.services.HelloReplyKt.Dsl._create(com.services.Hello.HelloReply.newBuilder()).apply { block() }._build()
object HelloReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.services.Hello.HelloReply.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.Hello.HelloReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.Hello.HelloReply = _builder.build()

    /**
     * <code>string message = 1;</code>
     */
    var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 1;</code>
     */
    fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * <code>.Enum enum = 2;</code>
     */
    var enum: com.services.Hello.Enum
      @JvmName("getEnum")
      get() = _builder.getEnum()
      @JvmName("setEnum")
      set(value) {
        _builder.setEnum(value)
      }
    /**
     * <code>.Enum enum = 2;</code>
     */
    fun clearEnum() {
      _builder.clearEnum()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.services.Hello.HelloReply.copy(block: com.services.HelloReplyKt.Dsl.() -> kotlin.Unit): com.services.Hello.HelloReply =
  com.services.HelloReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
