// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: login.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.services;

@kotlin.jvm.JvmName("-initializeloginRequest")
public inline fun loginRequest(block: com.services.LoginRequestKt.Dsl.() -> kotlin.Unit): com.services.Login.LoginRequest =
  com.services.LoginRequestKt.Dsl._create(com.services.Login.LoginRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `LoginRequest`
 */
public object LoginRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.services.Login.LoginRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.Login.LoginRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.Login.LoginRequest = _builder.build()

    /**
     * `string phoneNumber = 1;`
     */
    public var phoneNumber: kotlin.String
      @JvmName("getPhoneNumber")
      get() = _builder.getPhoneNumber()
      @JvmName("setPhoneNumber")
      set(value) {
        _builder.setPhoneNumber(value)
      }
    /**
     * `string phoneNumber = 1;`
     */
    public fun clearPhoneNumber() {
      _builder.clearPhoneNumber()
    }

    /**
     * `string password = 2;`
     */
    public var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * `string password = 2;`
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }

    /**
     * `bool use_password = 3;`
     */
    public var usePassword: kotlin.Boolean
      @JvmName("getUsePassword")
      get() = _builder.getUsePassword()
      @JvmName("setUsePassword")
      set(value) {
        _builder.setUsePassword(value)
      }
    /**
     * `bool use_password = 3;`
     */
    public fun clearUsePassword() {
      _builder.clearUsePassword()
    }

    /**
     * `optional string countryCode = 4;`
     */
    public var countryCode: kotlin.String
      @JvmName("getCountryCode")
      get() = _builder.getCountryCode()
      @JvmName("setCountryCode")
      set(value) {
        _builder.setCountryCode(value)
      }
    /**
     * `optional string countryCode = 4;`
     */
    public fun clearCountryCode() {
      _builder.clearCountryCode()
    }
    /**
     * `optional string countryCode = 4;`
     * @return Whether the countryCode field is set.
     */
    public fun hasCountryCode(): kotlin.Boolean {
      return _builder.hasCountryCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.services.Login.LoginRequest.copy(block: `com.services`.LoginRequestKt.Dsl.() -> kotlin.Unit): com.services.Login.LoginRequest =
  `com.services`.LoginRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

