//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

package com.services;

@kotlin.jvm.JvmSynthetic
inline fun messageInfo(block: com.services.MessageInfoKt.Dsl.() -> kotlin.Unit): com.services.Message.MessageInfo =
  com.services.MessageInfoKt.Dsl._create(com.services.Message.MessageInfo.newBuilder()).apply { block() }._build()
object MessageInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.services.Message.MessageInfo.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.Message.MessageInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.Message.MessageInfo = _builder.build()

    /**
     * <code>string sender = 1;</code>
     */
    var sender: kotlin.String
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * <code>string sender = 1;</code>
     */
    fun clearSender() {
      _builder.clearSender()
    }

    /**
     * <code>string messageId = 2;</code>
     */
    var messageId: kotlin.String
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * <code>string messageId = 2;</code>
     */
    fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * <code>string text = 3;</code>
     */
    var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * <code>string text = 3;</code>
     */
    fun clearText() {
      _builder.clearText()
    }

    /**
     * <code>string reciever = 4;</code>
     */
    var reciever: kotlin.String
      @JvmName("getReciever")
      get() = _builder.getReciever()
      @JvmName("setReciever")
      set(value) {
        _builder.setReciever(value)
      }
    /**
     * <code>string reciever = 4;</code>
     */
    fun clearReciever() {
      _builder.clearReciever()
    }

    /**
     * <code>string contentType = 5;</code>
     */
    var contentType: kotlin.String
      @JvmName("getContentType")
      get() = _builder.getContentType()
      @JvmName("setContentType")
      set(value) {
        _builder.setContentType(value)
      }
    /**
     * <code>string contentType = 5;</code>
     */
    fun clearContentType() {
      _builder.clearContentType()
    }

    /**
     * <code>string timestamp = 6;</code>
     */
    var timestamp: kotlin.String
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>string timestamp = 6;</code>
     */
    fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * <code>bool deliverStatus = 7;</code>
     */
    var deliverStatus: kotlin.Boolean
      @JvmName("getDeliverStatus")
      get() = _builder.getDeliverStatus()
      @JvmName("setDeliverStatus")
      set(value) {
        _builder.setDeliverStatus(value)
      }
    /**
     * <code>bool deliverStatus = 7;</code>
     */
    fun clearDeliverStatus() {
      _builder.clearDeliverStatus()
    }

    /**
     * <code>bool readStatus = 8;</code>
     */
    var readStatus: kotlin.Boolean
      @JvmName("getReadStatus")
      get() = _builder.getReadStatus()
      @JvmName("setReadStatus")
      set(value) {
        _builder.setReadStatus(value)
      }
    /**
     * <code>bool readStatus = 8;</code>
     */
    fun clearReadStatus() {
      _builder.clearReadStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.services.Message.MessageInfo.copy(block: com.services.MessageInfoKt.Dsl.() -> kotlin.Unit): com.services.Message.MessageInfo =
  com.services.MessageInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()
