// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.services;

@kotlin.jvm.JvmName("-initializemessageUpdateResponse")
public inline fun messageUpdateResponse(block: com.services.MessageUpdateResponseKt.Dsl.() -> kotlin.Unit): com.services.Message.MessageUpdateResponse =
  com.services.MessageUpdateResponseKt.Dsl._create(com.services.Message.MessageUpdateResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `MessageUpdateResponse`
 */
public object MessageUpdateResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.services.Message.MessageUpdateResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.Message.MessageUpdateResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.Message.MessageUpdateResponse = _builder.build()

    /**
     * `string sender = 1;`
     */
    public var sender: kotlin.String
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * `string sender = 1;`
     */
    public fun clearSender() {
      _builder.clearSender()
    }

    /**
     * `string reciever = 2;`
     */
    public var reciever: kotlin.String
      @JvmName("getReciever")
      get() = _builder.getReciever()
      @JvmName("setReciever")
      set(value) {
        _builder.setReciever(value)
      }
    /**
     * `string reciever = 2;`
     */
    public fun clearReciever() {
      _builder.clearReciever()
    }

    /**
     * `string messageId = 3;`
     */
    public var messageId: kotlin.String
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * `string messageId = 3;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `bool deliverStatus = 4;`
     */
    public var deliverStatus: kotlin.Boolean
      @JvmName("getDeliverStatus")
      get() = _builder.getDeliverStatus()
      @JvmName("setDeliverStatus")
      set(value) {
        _builder.setDeliverStatus(value)
      }
    /**
     * `bool deliverStatus = 4;`
     */
    public fun clearDeliverStatus() {
      _builder.clearDeliverStatus()
    }

    /**
     * `bool readStatus = 5;`
     */
    public var readStatus: kotlin.Boolean
      @JvmName("getReadStatus")
      get() = _builder.getReadStatus()
      @JvmName("setReadStatus")
      set(value) {
        _builder.setReadStatus(value)
      }
    /**
     * `bool readStatus = 5;`
     */
    public fun clearReadStatus() {
      _builder.clearReadStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.services.Message.MessageUpdateResponse.copy(block: `com.services`.MessageUpdateResponseKt.Dsl.() -> kotlin.Unit): com.services.Message.MessageUpdateResponse =
  `com.services`.MessageUpdateResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

