// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.services;

@kotlin.jvm.JvmName("-initializemessageInfo")
public inline fun messageInfo(block: com.services.MessageInfoKt.Dsl.() -> kotlin.Unit): com.services.Message.MessageInfo =
  com.services.MessageInfoKt.Dsl._create(com.services.Message.MessageInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `MessageInfo`
 */
public object MessageInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.services.Message.MessageInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.Message.MessageInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.Message.MessageInfo = _builder.build()

    /**
     * `string sender = 1;`
     */
    public var sender: kotlin.String
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * `string sender = 1;`
     */
    public fun clearSender() {
      _builder.clearSender()
    }

    /**
     * `string messageId = 2;`
     */
    public var messageId: kotlin.String
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * `string messageId = 2;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `string text = 3;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * `string text = 3;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * `string reciever = 4;`
     */
    public var reciever: kotlin.String
      @JvmName("getReciever")
      get() = _builder.getReciever()
      @JvmName("setReciever")
      set(value) {
        _builder.setReciever(value)
      }
    /**
     * `string reciever = 4;`
     */
    public fun clearReciever() {
      _builder.clearReciever()
    }

    /**
     * `string contentType = 5;`
     */
    public var contentType: kotlin.String
      @JvmName("getContentType")
      get() = _builder.getContentType()
      @JvmName("setContentType")
      set(value) {
        _builder.setContentType(value)
      }
    /**
     * `string contentType = 5;`
     */
    public fun clearContentType() {
      _builder.clearContentType()
    }

    /**
     * `string timestamp = 6;`
     */
    public var timestamp: kotlin.String
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * `string timestamp = 6;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * `bool deliverStatus = 7;`
     */
    public var deliverStatus: kotlin.Boolean
      @JvmName("getDeliverStatus")
      get() = _builder.getDeliverStatus()
      @JvmName("setDeliverStatus")
      set(value) {
        _builder.setDeliverStatus(value)
      }
    /**
     * `bool deliverStatus = 7;`
     */
    public fun clearDeliverStatus() {
      _builder.clearDeliverStatus()
    }

    /**
     * `bool readStatus = 8;`
     */
    public var readStatus: kotlin.Boolean
      @JvmName("getReadStatus")
      get() = _builder.getReadStatus()
      @JvmName("setReadStatus")
      set(value) {
        _builder.setReadStatus(value)
      }
    /**
     * `bool readStatus = 8;`
     */
    public fun clearReadStatus() {
      _builder.clearReadStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.services.Message.MessageInfo.copy(block: `com.services`.MessageInfoKt.Dsl.() -> kotlin.Unit): com.services.Message.MessageInfo =
  `com.services`.MessageInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

