// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.services;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\032\013login.proto\032\016register.p" +
      "roto\032\totp.proto\032\rcontact.proto\032\rmessage." +
      "proto\032\nauth.proto\032\nuser.proto\032\021keyexchan" +
      "ge.proto2\230\003\n\010Services\022(\n\005Login\022\r.LoginRe" +
      "quest\032\016.LoginResponse\"\000\0221\n\010Register\022\020.Re" +
      "gisterRequest\032\021.RegisterResponse\"\000\022\"\n\003Ot" +
      "p\022\013.OtpRequest\032\014.OtpResponse\"\000\0222\n\020Valida" +
      "teContacts\022\r.ContactsList\032\r.ContactsList" +
      "\"\000\022\030\n\004Send\022\006.Event\032\006.Event\"\000\022@\n\rmessageU" +
      "pdate\022\025.MessageUpdateRequest\032\026.MessageUp" +
      "dateResponse\"\000\022,\n\013VerifyToken\022\014.AuthRequ" +
      "est\032\r.AuthResponse\"\000\022\034\n\nsavePubKey\022\005.Use" +
      "r\032\005.User\"\000\022/\n\thandShake\022\017.PubKeyExchange" +
      "\032\017.PubKeyExchange\"\000B\023\n\014com.servicesZ\003/pb" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.services.Login.getDescriptor(),
          com.services.Register.getDescriptor(),
          com.services.Otp.getDescriptor(),
          com.services.ContactOuterClass.getDescriptor(),
          com.services.Message.getDescriptor(),
          com.services.Auth.getDescriptor(),
          com.services.UserOuterClass.getDescriptor(),
          com.services.Keyexchange.getDescriptor(),
        });
    com.services.Login.getDescriptor();
    com.services.Register.getDescriptor();
    com.services.Otp.getDescriptor();
    com.services.ContactOuterClass.getDescriptor();
    com.services.Message.getDescriptor();
    com.services.Auth.getDescriptor();
    com.services.UserOuterClass.getDescriptor();
    com.services.Keyexchange.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
