//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: user.proto

package com.services;

@kotlin.jvm.JvmSynthetic
inline fun user(block: com.services.UserKt.Dsl.() -> kotlin.Unit): com.services.UserOuterClass.User =
  com.services.UserKt.Dsl._create(com.services.UserOuterClass.User.newBuilder()).apply { block() }._build()
object UserKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.services.UserOuterClass.User.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.services.UserOuterClass.User.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.services.UserOuterClass.User = _builder.build()

    /**
     * <code>optional string username = 1;</code>
     */
    var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>optional string username = 1;</code>
     */
    fun clearUsername() {
      _builder.clearUsername()
    }
    /**
     * <code>optional string username = 1;</code>
     * @return Whether the username field is set.
     */
    fun hasUsername(): kotlin.Boolean {
      return _builder.hasUsername()
    }

    /**
     * <code>optional string password = 2;</code>
     */
    var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * <code>optional string password = 2;</code>
     */
    fun clearPassword() {
      _builder.clearPassword()
    }
    /**
     * <code>optional string password = 2;</code>
     * @return Whether the password field is set.
     */
    fun hasPassword(): kotlin.Boolean {
      return _builder.hasPassword()
    }

    /**
     * <code>optional string email = 3;</code>
     */
    var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>optional string email = 3;</code>
     */
    fun clearEmail() {
      _builder.clearEmail()
    }
    /**
     * <code>optional string email = 3;</code>
     * @return Whether the email field is set.
     */
    fun hasEmail(): kotlin.Boolean {
      return _builder.hasEmail()
    }

    /**
     * <code>string phoneNumber = 4;</code>
     */
    var phoneNumber: kotlin.String
      @JvmName("getPhoneNumber")
      get() = _builder.getPhoneNumber()
      @JvmName("setPhoneNumber")
      set(value) {
        _builder.setPhoneNumber(value)
      }
    /**
     * <code>string phoneNumber = 4;</code>
     */
    fun clearPhoneNumber() {
      _builder.clearPhoneNumber()
    }

    /**
     * <code>optional string countryCode = 5;</code>
     */
    var countryCode: kotlin.String
      @JvmName("getCountryCode")
      get() = _builder.getCountryCode()
      @JvmName("setCountryCode")
      set(value) {
        _builder.setCountryCode(value)
      }
    /**
     * <code>optional string countryCode = 5;</code>
     */
    fun clearCountryCode() {
      _builder.clearCountryCode()
    }
    /**
     * <code>optional string countryCode = 5;</code>
     * @return Whether the countryCode field is set.
     */
    fun hasCountryCode(): kotlin.Boolean {
      return _builder.hasCountryCode()
    }

    /**
     * <code>optional .google.protobuf.Timestamp updatedAt = 6;</code>
     */
    var updatedAt: com.google.protobuf.Timestamp
      @JvmName("getUpdatedAt")
      get() = _builder.getUpdatedAt()
      @JvmName("setUpdatedAt")
      set(value) {
        _builder.setUpdatedAt(value)
      }
    /**
     * <code>optional .google.protobuf.Timestamp updatedAt = 6;</code>
     */
    fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }
    /**
     * <code>optional .google.protobuf.Timestamp updatedAt = 6;</code>
     * @return Whether the updatedAt field is set.
     */
    fun hasUpdatedAt(): kotlin.Boolean {
      return _builder.hasUpdatedAt()
    }

    /**
     * <code>string uuid = 7;</code>
     */
    var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * <code>string uuid = 7;</code>
     */
    fun clearUuid() {
      _builder.clearUuid()
    }

    /**
     * <code>string token = 8;</code>
     */
    var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * <code>string token = 8;</code>
     */
    fun clearToken() {
      _builder.clearToken()
    }

    /**
     * <code>optional string pubKey = 9;</code>
     */
    var pubKey: kotlin.String
      @JvmName("getPubKey")
      get() = _builder.getPubKey()
      @JvmName("setPubKey")
      set(value) {
        _builder.setPubKey(value)
      }
    /**
     * <code>optional string pubKey = 9;</code>
     */
    fun clearPubKey() {
      _builder.clearPubKey()
    }
    /**
     * <code>optional string pubKey = 9;</code>
     * @return Whether the pubKey field is set.
     */
    fun hasPubKey(): kotlin.Boolean {
      return _builder.hasPubKey()
    }

    /**
     * <pre>
     * ⚠️WARNING: For testing.Need to be removed later
     * </pre>
     *
     * <code>optional string privKey = 10;</code>
     */
    var privKey: kotlin.String
      @JvmName("getPrivKey")
      get() = _builder.getPrivKey()
      @JvmName("setPrivKey")
      set(value) {
        _builder.setPrivKey(value)
      }
    /**
     * <pre>
     * ⚠️WARNING: For testing.Need to be removed later
     * </pre>
     *
     * <code>optional string privKey = 10;</code>
     */
    fun clearPrivKey() {
      _builder.clearPrivKey()
    }
    /**
     * <pre>
     * ⚠️WARNING: For testing.Need to be removed later
     * </pre>
     *
     * <code>optional string privKey = 10;</code>
     * @return Whether the privKey field is set.
     */
    fun hasPrivKey(): kotlin.Boolean {
      return _builder.hasPrivKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.services.UserOuterClass.User.copy(block: com.services.UserKt.Dsl.() -> kotlin.Unit): com.services.UserOuterClass.User =
  com.services.UserKt.Dsl._create(this.toBuilder()).apply { block() }._build()
