//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

@kotlin.jvm.JvmSynthetic
inline fun messageUpdateRequest(block: MessageUpdateRequestKt.Dsl.() -> kotlin.Unit): Message.MessageUpdateRequest =
  MessageUpdateRequestKt.Dsl._create(Message.MessageUpdateRequest.newBuilder()).apply { block() }._build()
object MessageUpdateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: Message.MessageUpdateRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Message.MessageUpdateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Message.MessageUpdateRequest = _builder.build()

    /**
     * <code>string fromPubKey = 1;</code>
     */
    var fromPubKey: kotlin.String
      @JvmName("getFromPubKey")
      get() = _builder.getFromPubKey()
      @JvmName("setFromPubKey")
      set(value) {
        _builder.setFromPubKey(value)
      }
    /**
     * <code>string fromPubKey = 1;</code>
     */
    fun clearFromPubKey() {
      _builder.clearFromPubKey()
    }

    /**
     * <code>string messageId = 2;</code>
     */
    var messageId: kotlin.String
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * <code>string messageId = 2;</code>
     */
    fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * <code>string deliverStatus = 3;</code>
     */
    var deliverStatus: kotlin.String
      @JvmName("getDeliverStatus")
      get() = _builder.getDeliverStatus()
      @JvmName("setDeliverStatus")
      set(value) {
        _builder.setDeliverStatus(value)
      }
    /**
     * <code>string deliverStatus = 3;</code>
     */
    fun clearDeliverStatus() {
      _builder.clearDeliverStatus()
    }

    /**
     * <code>string readStatus = 4;</code>
     */
    var readStatus: kotlin.String
      @JvmName("getReadStatus")
      get() = _builder.getReadStatus()
      @JvmName("setReadStatus")
      set(value) {
        _builder.setReadStatus(value)
      }
    /**
     * <code>string readStatus = 4;</code>
     */
    fun clearReadStatus() {
      _builder.clearReadStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun Message.MessageUpdateRequest.copy(block: MessageUpdateRequestKt.Dsl.() -> kotlin.Unit): Message.MessageUpdateRequest =
  MessageUpdateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
