// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: middleware/middleware.proto

package com.fury.messenger.middlewaregrpc;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.middleware.PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
