name: Messenger CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  run-lint-middleware:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: NPM clean install
        run: npm ci
        shell: bash
        working-directory: ./middleware
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run linter
        run: npm run lint
        shell: bash
        working-directory: ./middleware
  run-lint-messsage-socket:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: NPM clean install
        run: npm ci
        shell: bash
        working-directory: ./messsage-socket
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run linter
        run: npm run lint
        shell: bash
        working-directory: ./messsage-socket
  run-build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned."
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory: ./frontend
      - name: Install dos2unix
        run: sudo apt-get install dos2unix
        shell: bash
      - name: Convert line endings
        run: dos2unix gradlew
        shell: bash
        working-directory: ./frontend
      - run: echo "Building Debug APK."
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        working-directory: ./frontend
      - run: echo "Build status report=${{ job.status }}."
  run-build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18.1"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Verify dependencies
        run: go mod verify
        shell: bash
        working-directory: ./backend

      - name: Build backend
        run: go build -v .
        working-directory: ./backend

      - name: Run go vet
        run: go vet ./...
        shell: bash
        working-directory: ./backend
